// File Magic Signatures
include "ft_exe.yara"
include "ft_rar.yara"
include "ft_zip.yara"
include "ft_pdf.yara"
include "ft_ole_cf.yara"
include "ft_swf.yara"
include "ft_office_open_xml.yara"
include "ft_rtf.yara"
include "ft_tar.yara"
include "ft_gzip.yara"
include "ft_jar.yara"
include "ft_cab.yara"
include "ft_elf.yara"
include "ft_java_class.yara"
include "ft_vbe.yara"
